services:
  # NestJS API service
  api:
    container_name: ${API_CONTAINER_NAME:-api}
    build:
      context: .
      args:
        NODE_ENV: ${APPLICATION_MODE:-development}
    ports:
      - '${PORT:-8000}:${PORT:-8000}'
    networks:
      - app-network
    restart: always
    environment:
      DATABASE_URL: mysql://${MYSQL_USERNAME}:${MYSQL_PASSWORD}@mysql:3306/${MYSQL_DATABASE}
      RABBITMQ_URI: amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672
    depends_on:
      - mysql
      - rabbitmq

  # RabbitMQ service
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - '15672:15672' # Management UI port
      - '5672:5672' # AMQP port
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-admin}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-admin}
    networks:
      - app-network

  # MySQL service
  mysql:
    image: mysql:8.1
    container_name: ${MYSQL_CONTAINER_NAME:-mysql-db}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-template_db}
      MYSQL_USER: ${MYSQL_USERNAME:-app_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-Pass1234@}
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      retries: 5
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
